// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hgmlsachjazvdvckmtlh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhnbWxzYWNoamF6dmR2Y2ttdGxoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4OTI4NjAsImV4cCI6MjA3MzQ2ODg2MH0.8cqLizOIWdmNFi4NzTBXBfiHC0ebu7KHwaRIrUJFB1k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});